# 1) Loading packages:

In [1]:
import struct
import gzip
import numpy as np
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt

# 2) Importing and transforming image data

In Machine Learning applications, we need data to be represented in the form of vectors/arrays/matrices/tensors depending on the dimensionality of our data. 

Tensors = Containers

A tensor is the basic building block of modern machine learning.
At its core it’s a data container. Mostly it contains numbers. Sometimes it even contains strings, but that’s rare. 

![alt text](https://cdn-images-1.medium.com/max/2000/1*_D5ZvufDS38WkhK9rK32hQ.jpeg)
![alt text](https://cdn-images-1.medium.com/max/2000/1*_D5ZvufDS38WkhK9rK32hQ.jpeg)


##        a) Examples of tensors using the mighty NumPy package

In the case of images, our data will be imported as a 4-D Tensor represented as

 (Number of images, Width of each image in pixels, Height of each image in pixels, Depth of image)


 3D Tensor= Time series

4D Tensor= Images

5D Tensor= Videos

### 0-D Tensor A.K.A "Scalar"


In [2]:
scalar = np.array(5)
scalar.ndim # Using "ndim" to get number of dimensions of the object

0

### 1-D Tensor A.K.A "Vector"

In [3]:
vector = np.array([1,2,3,4])
vector.ndim # Using "ndim" to get number of dimensions of the object

1

### 2-D Tensor A.K.A "Matrix"

In [4]:
matrix = np.array([[5,10,15,30,25],
              [20,30,65,70,90],
              [7,80,95,20,30]])
matrix.ndim # Using "ndim" to get number of dimensions of the object

2

### 3-D Tensor A.K.A .... a cube of numbers :) That's when tensors start being useful


In [5]:
threedtensor = np.array([[[5,10,15,30,25],
               [20,30,65,70,90],
               [7,80,95,20,30]],

               [[3,0,5,0,45],
               [12,-2,6,7,90],
               [18,-9,95,120,30]],
               
               [[17,13,25,30,15],
               [23,36,9,7,80],
               [1,-7,-5,22,3]]])
threedtensor.ndim

3

### Now, we can proceed to load our binary data using a function which I found online. The function is "defined" as read_idx. The function components are as follows:
a) gzip: is a package to open gzip files

b) open: is a function that opens files to read, write, or append. In that function we specify 'rb' which means "read binary"

c) "with" gzip and open we will "unpack" the binary file using a package called "struct" based on the order and format of the binary data



In [2]:
def read_idx(filename):
    with gzip.open(filename, 'rb') as f:
        zero, data_type, dims = struct.unpack('>HBB', f.read(4))
        shape = tuple(struct.unpack('>I', f.read(4))[0] for d in range(dims))
        return np.fromstring(f.read(), dtype=np.uint8).reshape(shape)

images_in_binary_format = read_idx('train-images-idx3-ubyte.gz')
labels_of_the_images = read_idx('train-labels-idx1-ubyte.gz')

images_in_binary_format = images_in_binary_format/255 # To make calculations easier we will make values range from 0 - 1

C:\Users\oshaat\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  """


### Lets look at the "Shape" of the data that we loaded in by using the "Shape" function from NumPy and figure out what we need to do in order to further prepare the data

In [3]:
images_in_binary_format

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [8]:
images_in_binary_format.shape

(60000, 28, 28)

In [9]:
labels_of_the_images

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [10]:
labels_of_the_images.shape

(60000,)

## B) To fully prepare the data for our Neural Network, we will "flatten" the image into a Vector of pixels using the "Reshape" function which can be used to manipulated matrices, arrays, and tensors
![alt text](https://miro.medium.com/max/940/0*teIkFyoG1mj8Ul-r)
![alt text](https://miro.medium.com/max/940/0*teIkFyoG1mj8Ul-r)

In [4]:
flattened_image = images_in_binary_format.reshape(60000,784)

## Furthermore, we need to find a way to have the network predict and perform calculations on specific digit labels. For that we will create a prediction class which will organize potential label values (0-9) and will show us a "1" in place of the image's label in a form of an array.

For that we use np.eye which generates an identity matrix of dimensions equivalent to the number of classes/digits we have

Return a 2-D array with ones on the diagonal and zeros elsewhere.

Example:

np.eye(3)
array([[ 1.,  0.,  0.],

   [ 0.,  1.,  0.],

   [ 0.,  0.,  1.]])
   

# When a [label] is placed after np.eye, np.eye acts as an array element index. So with only one element in it, it returns given number of rows element as array. This method is referred to as "One-Hot Encoding"

Examples:

np.eye(3)[1]

array([ 0.,  1.,  0.])


np.eye(3)[2]

array([ 0.,  0.,  1.])

In [5]:
n_digits = 10 #Number of digits to classify (0-9)
images_labels_classification_array = np.eye(n_digits)[labels_of_the_images.astype('int32')] #Creating a 60,000 x 10 matrix to show labels in an array format
images_labels_classification_array

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [13]:
images_labels_classification_array.shape

(60000, 10)

# 3) Fun part - Creating a plain vanilla "Fully Connected Neural Network" A.K.A "Multi-Layer Perceptron

## A) How are Neurons connected? What are the layers in the middle?

  1. The layers in the middle: are called "Hidden Layers" which the user specifies. There is no specific rule to how many neurons should be in each hidden layers or what exactly goes into it. However, what goes into the hidden layers is referred to as the "Architecture" of the network, and it is considered an art in the field.

  2. The layers are connected: by inputing all 784 pixels into the first layer, with each neuron representing the value which corresponds to the brightness of each image. The "pattern" in the neurons' brightness causes a specific pattern in the hidden layers, which lead to a final output/prediction.

  3. The last layer represents the possible digits from (0-9). The values/activation within the neurons in the last layer represent the probability of the image fed into the network having a label of 0-1-2-3-4-5-6-7-8- or 9. Of course, the network classifies the digit based on the neuron with the highest probability.

![alt text](https://thumbs.gfycat.com/DeadlyDeafeningAtlanticblackgoby-size_restricted.gif)

In [6]:
number_of_node_in_hidden_layer = 64 # Architecture


##B) What is a neuron and How are the Neurons fed into the network?


   It's just a thing that holds a number (represented as a circle). In our case, the number is a value from 0-1 (which was originally a value from 0-255). And for EACH IMAGE we have a total of 784 neurons (28 x 28 flattened images) as the INPUT to the network. The value for the MNIST dataset represents the "greyscale" value of the corresponding pixel.

![alt text](https://miro.medium.com/max/1446/1*cLsTCWtUL1GYBUv8vnbOxw.jpeg)

In [7]:
number_of_input_neurons = flattened_image.shape[1] # This is 28 x 28 = 784

##C) How do the layers in the middle work exactly? (This is an explanation just to expalain intuition behind it)

- Simple answer: The middle layers try to identify specific "knobs"/"parameters" to identify:

  1.   patterns, loops, and maybe edges in specific regions within the handwritten image
  2.   In this case the "parameters" are weights assigned to each "connection" between the images' neurons and the neurons in the first hidden layer. The network learns by adjusting the weights in areas where there is handwriting

  3. The weighted sum is then computed.


![alt text](https://thumbs.gfycat.com/BabyishGeneralFruitfly-small.gif)

- We start off by "initializing" the parameters and get the network to start learning. We initialize using NumPy's "np.random.rand" function for random weights, and "np.zeros" for zero initial bias terms

In [8]:
# 2 layers before passing into activation function which squishes values into 0-1 range
W1 = np.random.randn(number_of_node_in_hidden_layer, number_of_input_neurons)# Connection weights layer 1
b1 = np.zeros((number_of_node_in_hidden_layer,1)) # Neurons bias terms output layer 1
W2 = np.random.randn(n_digits, number_of_node_in_hidden_layer) # Connection weights ourput layer
b2 = np.zeros((n_digits,1)) # Neurons bias terms output layer

# The network has the following number of parameters:
# W1 = 784 * 64 => 4704 weights
# b1 = 64 => 64 biases
# W2 = 64 x 10 => 640 weights
# b2 = 10 => 10 biases
# A TOTAL OF 5,418 parameters need to be tweaked while putting into account the relationship between each of them

In [9]:
W1.shape # Shape of weights matrix (64 connections per input neuron into first hidden layer)

(64, 784)

In [10]:
b1.shape # Shape of bias terms vector (64 neurons in first hidden layers)

(64, 1)

##D) How does the final output/prediction computed?

  - After taking the weighted sum, we pass each neuron's output through an "Activation Function" which squishes the value (again) to 0-1 to represent probability. For this we will use a "sigmoid" function which is pretty much a logistic curve. However, we dont pass it through the sigmoid untill we add a "bias" term which allows us to specify exactly when we want the neuron to meaningfully light up or be activated

![alt text](https://www.researchgate.net/profile/Tali_Leibovich-Raveh/publication/325868989/figure/fig2/AS:639475206074368@1529474178211/A-Basic-sigmoid-function-with-two-parameters-c1-and-c2-as-commonly-used-for-subitizing.png)

  - We will define this function using NumPy as well. We will use the "np.exp" to get the exponent

In [11]:
def sigmoid(z):
    sig = 1/(1+np.exp(-z))
    return sig

##E) How does the network learn what's right and what's wrong?

 - It compared what it predicted VS. what the actual label was and computes the "loss". This is similar to the Least Squares in regression and each problem would have a unique Loss Function (Objective Function)

![alt text](https://images.slideplayer.com/16/4913205/slides/slide_6.jpg)

 - For the loss function, we get the sum of the element wise multiplication. Therefore we get the "np.sum" of the element wise products of the elements within "np.multiply". Which in this case are Y = Actual Value and Y_hat = Predicted Value

In [12]:
def compute_multiclass_loss(Y, Y_hat):
    L_sum = np.sum(np.multiply(Y, np.log(Y_hat)))
    m = 60000
    L = -(1/m) * L_sum
    return L

- The network tries to minimize the loss as much as it can by taking the derivative of the function 

![alt text](https://miro.medium.com/max/1204/1*t6OiVIMKw3SBjNzj-lp_Fw.png)

##F) Lets write a loop to start training the model

  - Steps within a loop:
  1. Create "skeleton of model
      - Create empty input neurons
      - Specify number of neurons in hidden layers
  2. Input image data into skeleton
  3. Multiply weights by image data and add bias terms to identify patterns
  4. Pass weighted sums through "Sigmoid activation function" to get probabilities
  5. Compute cost/loss based on probability output versus actual label using loss function
  6. Fix weights by using BackPropagation

![alt text](http://hmkcode.github.io/images/ai/bp_update_formula.png)

A more mathematical point of view
![alt text](https://slideplayer.com/slide/13458681/80/images/26/Cross-Entropy+Avoids+the+Slow+Learning.jpg)
![alt text](https://i.stack.imgur.com/pYVzl.png)
  
  7. Finally, use learned parameters to predict output values


 RECAP OF VARIABLES WE DEFINED BEFORE:
- W1 = (784 * 64) => 4704 weights (initialized randomly)
- b1 = (64) => 64 biases (initialized at zero)
- W2 = (64) x 10 => 640 weights (initialized randomly)
- b2 = (10) => 10 biases (initialized at zero)
- flattened_image (60000,784) 60 thousand images with 784 pixels in form of a vector 
- images_labels_classification_array (One hot encoded classification labels)
- number_of_node_in_hidden_layer (Number of nodes we specific as 64 in hidden layer)
- number_of_input_neurons (The number of neurons/pixels of the image, we start it off by being empty)
- sigmoid (The function that squishes output into 0-1 range)
- compute_multiclass_loss (The cross-entropy function that tries to minimize the error between prediction and actual label)





In [16]:
n_x = X.shape[1]
n_h = 64 # Architecture
learning_rate = 10
W1 = np.random.randn(n_h, n_x)# Neurons weights
b1 = np.zeros((n_h,1)) # Neurons intercepts
W2 = np.random.randn(n_digits, n_h) # Probability/weights of prediction
b2 = np.zeros((n_digits,1))
epochs = 1000
for epoch in range(epochs):
    Z1 = np.matmul(W1,X.T)+b1 # Feed forward prop
    A1 = sigmoid(Z1) # Feedforward activation
    Z2 = np.matmul(W2,A1)+b2 
    A2 = np.exp(Z2) / np.sum(np.exp(Z2), axis=0) #Softmax
    
    cost = compute_multiclass_loss(images_labels_classification_array,A2.T)
    
    # Cross entropy cost
    dZ2 = A2.T - images_labels_classification_array
    dW2 = (1./y.shape[0])*np.matmul(A1,dZ2)
    db2 = (1./y.shape[0])*np.sum(dZ2,axis=0,keepdims=True)
    
    dA1 = np.matmul(dZ2,W2)
    dZ1 = dA1.T*sigmoid(Z1)*(1-sigmoid(Z1))
    dW1 = (1./y.shape[0]) * np.matmul(dZ1,X)
    db1 = (1./y.shape[0]) * np.sum(dZ1, axis=0, keepdims=True)
    
    W2 = W2 - learning_rate*dW2.T
    b2 = b2 - learning_rate*db2.T
    W1 = W1 - learning_rate*dW1
    b1 = b1 - learning_rate*db1
    
    if(epoch % 5 == 0):
        print('Epoch', epoch, 'cost: ', cost)

print("Final cost:", cost)

Epoch 0 cost:  9.084404420526242
Epoch 5 cost:  7.629835317341987
Epoch 10 cost:  1.4751061828881564
Epoch 15 cost:  1.1597604518580427
Epoch 20 cost:  0.9813871470527742
Epoch 25 cost:  0.8583677807581396
Epoch 30 cost:  0.7743159138250205
Epoch 35 cost:  0.7123862817493861
Epoch 40 cost:  0.6646142143400833
Epoch 45 cost:  0.6269977787360498
Epoch 50 cost:  0.5962393957064208
Epoch 55 cost:  0.5702965291277824
Epoch 60 cost:  0.5480569906556133
Epoch 65 cost:  0.5285646340029159
Epoch 70 cost:  0.5112060650601117
Epoch 75 cost:  0.49560729190849884
Epoch 80 cost:  0.48149326300123846
Epoch 85 cost:  0.4686426886254633
Epoch 90 cost:  0.45684520713255256
Epoch 95 cost:  0.445925117785683
Epoch 100 cost:  0.43575783227262277
Epoch 105 cost:  0.42625964276645106
Epoch 110 cost:  0.41737134173777735
Epoch 115 cost:  0.40903359423853847
Epoch 120 cost:  0.40118828894847824
Epoch 125 cost:  0.39378924010589705
Epoch 130 cost:  0.386803322225323
Epoch 135 cost:  0.38020462138788735
Epoch 14

In [18]:
Z1 = np.matmul(W1,X.T)+b1 # First layer output
A1 = sigmoid(Z1) # First layer activation
Z2 = np.matmul(W2,A1.T)+b2 # Output layer output
A2 = sigmoid(Z2) #Output layer output
prediction = np.array([i.argmax() for i in A2.T]) #Predictions by taking the label with the maximum probability in the final layer A2
(60000-(prediction!=y).sum())/60000 # Simple accuracy measure

0.95865